backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/static"
public_folder: "/static"
collections:
  - name: "blog"
    label: "Blog"
    files:
      - name: "posts"
        label: "Posts"
        folder: "src/blog"
        slug: "{{slug}}"
        preview_path: "blog/{{slug}}"
        create: true
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Tags", name: "tags", widget: "list", allow_add: true}
          - {label: "Body", name: "body", widget: "markdown"}